### ISSUE TITLE
[Core] Magic Resistance Checklist (ICC/RS)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4808]
**Links:** http://worldoflogs.com/reports/up5rno2y5w0lta6h/
https://web.archive.org/web/20130610125321/http://elitistjerks.com/f15/t44675-resistance_mechanics_wotlk/

> ### _**Absorbs apply before resistances**_

**The following list shows the expected behavior of those spells:**

### **Single School (Resisted at ~20-25%)**

_Trash_

- [x] [Aura of Darkness (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72629/)
- [x] [Glacial Blast (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71029/)
- [x] [Plague Stench (Nature)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71161/)

_Marrowgar_

- [x] [Coldflame (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/70825/)

_Lady Deathwhisper_

- [ ] [Death and Decay (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72110/)
- [ ] [Frostbolt (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72502/) *
- [ ] [Frostbolt Volley (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72908/) *
- [ ] [Shadow Bolt (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72504/)

> *Frostbolt and other spells with a similar structure in the Classic branch are now considered binary (it was changed in patch 2.3), which gives Frost Mages a certain edge over Fire Mages; these spells now ignore 6% of resistance mitigation imposed by the boss' level difference.
> 
> Binary spells are now incapable of partially resisting and magic resistance mitigation is directly translated into a chance for a complete resist.

_Festergut_

- [ ] [Blighted Spores (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73034/)
- [ ] [Gaseous Blight (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/70137/)

_Professor Putricide_

- [ ] [Choking Gas (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72620/)

_Blood Prince Council_

- [ ] [Glittering Sparks (Fire)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72798/)
- [ ] [Shadow Prison (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72999/) *Behaves like frostbolt from above

_Blood Queen Lana'thel_

- [ ] [Shroud of Sorrow (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71700/)
- [ ] [Swarming Shadows (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72640/)

_Sindragosa_

- [ ] [Backlash (Arcane)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71046/)
- [ ] [Blistering Cold (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71049/)
- [ ] [Chilled to the Bone (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/70106/)
- [ ] [Frost Aura (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71052/)
- [ ] [Frost Breath (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71058/)
- [ ] [Ice Tomb (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/70157/)

_Lich King_

- [ ] [Defile (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73710/)
- [ ] [Explosion (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73805/)
- [ ] [Fury of Frostmourne (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72350/)
- [ ] [Harvest Soul (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73655/)
- [x] [Ice Pulse (Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73778/)
- [ ] [Infest (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73781/)
- [ ] [Life Siphon (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73784/)
- [ ] [Pain and Suffering (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73790/)
- [ ] [Soul Shriek (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73802/)
- [ ] [Spirit Burst (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73808/)

_Ruby Sanctum_

- [ ] [Blast Nova (Fire)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71029/)
- [ ] [Blazing Aura (Fire)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/75887/)
- [ ] [Combustion (Fire)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/75884/)
- [ ] [Consumption (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/75876/)
- [ ] [Flame Breath (Fire)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/74528/)
- [ ] [Meteor Strike (Fire)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/75952/)

### **Multi-school, double dips (Resisted at ~50-60%)**

_Professor Putricide_

- [x] [Mutated Transformation (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72513/) Issue #4113 

_Blood Queen Lana'thel_

- [x] [Twilight Bloodbolt (Arcane/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71821/) Issue #4619 

### **Multi-school, only uses lowest (Resisted at ~15% without double 130 resist aura)**

_Lady Deathwhisper_

- [ ] [Deathchill Bolt/Blast (Shadow/Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72489/)
- [ ] [Vengeful Blast (Shadow/Frost)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72012/)

_Blood Queen Lana'thel_

- [ ] [Bloodbolt Splash (Arcane/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71483/)

_Rotface_

- [ ] [Mutated Infection (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73023/)
- [ ] [Ooze Flood (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71588/)
- [ ] [Radiating Ooze (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73027/)
- [ ] [Slime Spray (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73190/)
- [ ] [Unstable Ooze Explosion (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73030/)
- [ ] [Weak Radiating Ooze (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73025/)
- [ ] [Vile Gas (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73174/)

_Festergut_

- [ ] [Gastric Bloat (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72553/)
- [ ] [Vile Gas (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73174/)

_Professor Putricide_

- [ ] [Malleable Goo (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72874/) *Behaves like frostbolt above
- [ ] [Slime Puddle (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72869/)
- [ ] [Volatile Ooze Adhesive (Nature/Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72838/)

### **Can't be resisted (Confirmed with multiple logs)**

_Festergut_

- [x] [Pungent Blight (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/73032/)

_Professor Putricide_

- [x] [Mutated Plague (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72507/)
- [x] [Ooze Eruption (Shadow/Nature)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72625/)
- [x] [Unbound Plague (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72856/)

_Blood Prince Council_

- [x] [Empowered Shadow Lance (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/72811/) Not affected by shadow resist, nuclei still lower damage

_Blood Queen Lana'thel_

- [x] [Blood Mirror (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/70821/)
- [x] [Pact of the Darkfallen (Shadow)](http://worldoflogs.com/reports/up5rno2y5w0lta6h/spell/71341/)

**Comment by Keader** [comment]
Implement Binary Resistence here? i dont think so... xd
but we can fix the "impossible to resist" ones

**Comment by Oganku** [comment]
It's possible that all of those work fine, it's just a case by case to see which ones might not.

**Comment by Keader** [comment]
Ok, spells with multiple schools already use lowest resistance to calculate damage.
Fixed all cases that should not be resisted.
I will not implement binary resistance here (yes, TC has it "working), because it cause alot of prolems. We will need alot of time to fix all issues and i belive that janitor dont want it (for now atm).

**Comment by Oganku** [comment]
Thanks a lot keader <3
